USE amz_search;
CREATE TABLE IF NOT EXISTS amz_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, keyword VARCHAR(200) NOT NULL, create_time DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
