@echo off
set JAVA=D:\Java\tools\jdk-21.0.11+10\bin\java.exe
set JARBASE=D:\Desktop\amazon-erp\amz-service
set LOGDIR=D:\Desktop\amazon-erp\.service-logs
set COMMON=-Xms256m -Xmx512m -Dspring.cloud.nacos.discovery.enabled=false -Dspring.cloud.nacos.config.enabled=false -DSEATA_ENABLED=false
set JWT=--spring.flyway.baseline-on-migrate=true --crypto.key=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY= --jwt.secret-key=local-e2e-secret-key-0123456789abcdef --AMZ_CRYPTO_KEY=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
set INFRA=--spring.redis.host=127.0.0.1 --spring.redis.port=6379 --spring.redis.password=amzpass --spring.data.redis.host=127.0.0.1 --spring.data.redis.port=6379 --spring.data.redis.password=amzpass --spring.rabbitmq.host=127.0.0.1

start "order" /min cmd /c ""%JAVA%" %COMMON% -jar %JARBASE%\amz-service-order\target\amz-service-order-1.0-SNAPSHOT.jar --server.port=8105 --spring.datasource.dynamic.datasource.master.url="jdbc:mysql://127.0.0.1:3307/amz_order?serverTimezone=Asia/Shanghai^&useSSL=false^&allowPublicKeyRetrieval=true" --spring.datasource.dynamic.datasource.slave.url="jdbc:mysql://127.0.0.1:3307/amz_order?serverTimezone=Asia/Shanghai^&useSSL=false^&allowPublicKeyRetrieval=true" --spring.datasource.dynamic.datasource.master.username=root --spring.datasource.dynamic.datasource.slave.username=root --spring.datasource.dynamic.datasource.master.password= --spring.datasource.dynamic.datasource.slave.password= %JWT% %INFRA% > "%LOGDIR%\order.log" 2>&1"

start "spapi" /min cmd /c ""%JAVA%" %COMMON% -jar %JARBASE%\amz-service-spapi\target\amz-service-spapi-1.0-SNAPSHOT.jar --server.port=8096 --spring.datasource.dynamic.datasource.master.url="jdbc:mysql://127.0.0.1:3307/amz_spapi?serverTimezone=Asia/Shanghai^&useSSL=false^&allowPublicKeyRetrieval=true" --spring.datasource.dynamic.datasource.slave.url="jdbc:mysql://127.0.0.1:3307/amz_spapi?serverTimezone=Asia/Shanghai^&useSSL=false^&allowPublicKeyRetrieval=true" --spring.datasource.dynamic.datasource.master.username=root --spring.datasource.dynamic.datasource.slave.username=root --spring.datasource.dynamic.datasource.master.password= --spring.datasource.dynamic.datasource.slave.password= %JWT% %INFRA% > "%LOGDIR%\spapi.log" 2>&1"

start "product" /min cmd /c ""%JAVA%" %COMMON% -jar %JARBASE%\amz-service-product\target\amz-service-product-1.0-SNAPSHOT.jar --server.port=8095 --spring.datasource.url="jdbc:mysql://127.0.0.1:3307/amz_product?serverTimezone=Asia/Shanghai^&useSSL=false^&allowPublicKeyRetrieval=true" --spring.datasource.username=root --spring.datasource.password= --spring.data.mongodb.password=x %JWT% %INFRA% > "%LOGDIR%\product.log" 2>&1"
