package com.amz.client;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.Map;

/**
 * Deterministic development/demo implementation for the {@code mock} profile.
 *
 * <p>It performs the same request validation as the real implementation, but
 * never resolves credentials or reaches the network. Response payloads come from
 * {@code /mock/fixtures.json} (generated by
 * {@code tools/contract-fixtures/generate_b_bucket_fixtures.py} from Amazon's own
 * published {@code x-amzn-api-sandbox} blocks, or the official response schema
 * when a sandbox block does not exist), so the demo profile exercises the same
 * response shapes callers see in production. Every payload carries a top-level
 * {@code synthetic=true} marker so demo output can never be mistaken for
 * platform data.</p>
 */
@Component
@Profile("mock")
public class MockSpApiOperationClient implements SpApiOperationClient {

    private static final String FIXTURE_RESOURCE = "/mock/fixtures.json";

    private final Map<String, JsonObject> payloadsByOperationId;

    public MockSpApiOperationClient() {
        this(loadFixtures());
    }

    MockSpApiOperationClient(Map<String, JsonObject> payloadsByOperationId) {
        this.payloadsByOperationId = payloadsByOperationId;
    }

    private static Map<String, JsonObject> loadFixtures() {
        try (InputStream in = MockSpApiOperationClient.class.getResourceAsStream(FIXTURE_RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(
                        "mock fixture resource missing: " + FIXTURE_RESOURCE
                                + "; regenerate via tools/contract-fixtures/generate_b_bucket_fixtures.py");
            }
            String json = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            JsonObject root = JsonParser.parseString(json).getAsJsonObject();
            java.util.Map<String, JsonObject> payloads = new java.util.LinkedHashMap<>();
            for (Map.Entry<String, com.google.gson.JsonElement> entry : root.entrySet()) {
                if (!entry.getValue().isJsonObject()) {
                    throw new IllegalStateException("mock fixture entry must be an object: " + entry.getKey());
                }
                payloads.put(entry.getKey(), entry.getValue().getAsJsonObject());
            }
            return java.util.Collections.unmodifiableMap(payloads);
        } catch (IOException e) {
            throw new UncheckedIOException("failed to load " + FIXTURE_RESOURCE, e);
        }
    }

    @Override
    public JsonObject execute(Long shopId,
                              String marketplaceId,
                              SpApiOperationSpec operation,
                              Map<String, String> pathParameters,
                              Map<String, String> queryParameters,
                              JsonObject body) {
        SpApiOperationClient.validateRequest(operation, pathParameters, queryParameters, body);
        JsonObject payload = payloadsByOperationId.get(operation.operationId());
        if (payload == null) {
            // fail-closed: catalog 增长而 fixture 未再生成时必须立刻显性失败，
            // 不允许退回旧的自造 envelope 混入非官方形状。
            throw new IllegalStateException(
                    "no synthetic fixture for operation " + operation.operationId()
                            + "; regenerate tools/contract-fixtures/generate_b_bucket_fixtures.py");
        }
        if (!payload.has("synthetic") || !payload.get("synthetic").getAsBoolean()) {
            throw new IllegalStateException(
                    "fixture for " + operation.operationId() + " lost its synthetic marker");
        }
        return payload.deepCopy();
    }
}
