package com.amz.client;

import com.google.gson.JsonObject;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * Deterministic development/demo implementation for the {@code mock} profile.
 *
 * <p>It performs the same request validation as the real implementation, but
 * never resolves credentials or reaches the network. The response is always
 * marked {@code synthetic=true} so callers cannot mistake it for platform data.</p>
 */
@Component
@Profile("mock")
public class MockSpApiOperationClient implements SpApiOperationClient {

    @Override
    public JsonObject execute(Long shopId,
                              String marketplaceId,
                              SpApiOperationSpec operation,
                              Map<String, String> pathParameters,
                              Map<String, String> queryParameters,
                              JsonObject body) {
        SpApiOperationClient.validateRequest(operation, pathParameters, queryParameters, body);
        JsonObject result = new JsonObject();
        result.addProperty("synthetic", true);
        result.addProperty("operationId", operation.operationId());
        result.addProperty("family", operation.family());
        result.addProperty("method", operation.method());
        result.addProperty("path", SpApiOperationClient.resolvePath(operation, pathParameters));
        result.addProperty("query", SpApiGateway.canonicalQuery(queryParameters));
        result.addProperty("shopId", shopId);
        result.addProperty("marketplaceId", marketplaceId);
        result.addProperty("message", "Synthetic SP-API response generated by mock profile");
        return result;
    }
}
