package com.amz.client;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Static operation catalog derived from the official SP-API OpenAPI snapshots.
 */
public final class SpApiOperationCatalog {

    private static final List<SpApiOperationSpec> OPERATIONS = List.of(
            new SpApiOperationSpec(
                    "notifications.getSubscriptions",
                    "notifications",
                    "GET",
                    "/notifications/v1/subscriptions",
                    List.of(200),
                    false,
                    false,
                    Set.of(),
                    Set.of("notificationTypes"),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.getSubscription",
                    "notifications",
                    "GET",
                    "/notifications/v1/subscriptions/{notificationType}",
                    List.of(200),
                    false,
                    false,
                    Set.of("notificationType"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.createSubscription",
                    "notifications",
                    "POST",
                    "/notifications/v1/subscriptions/{notificationType}",
                    List.of(200),
                    false,
                    true,
                    Set.of("notificationType"),
                    Set.of(),
                    Set.of("destinationId", "payloadVersion")),
            new SpApiOperationSpec(
                    "notifications.getSubscriptionById",
                    "notifications",
                    "GET",
                    "/notifications/v1/subscriptions/{notificationType}/{subscriptionId}",
                    List.of(200),
                    true,
                    false,
                    Set.of("notificationType", "subscriptionId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.deleteSubscriptionById",
                    "notifications",
                    "DELETE",
                    "/notifications/v1/subscriptions/{notificationType}/{subscriptionId}",
                    List.of(200),
                    true,
                    false,
                    Set.of("notificationType", "subscriptionId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.sendTestNotification",
                    "notifications",
                    "POST",
                    "/notifications/v1/subscriptions/{notificationType}/testNotification",
                    List.of(200),
                    true,
                    true,
                    Set.of("notificationType"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.getDestinations",
                    "notifications",
                    "GET",
                    "/notifications/v1/destinations",
                    List.of(200),
                    true,
                    false,
                    Set.of(),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.createDestination",
                    "notifications",
                    "POST",
                    "/notifications/v1/destinations",
                    List.of(200),
                    true,
                    true,
                    Set.of(),
                    Set.of(),
                    Set.of("name", "resourceSpecification")),
            new SpApiOperationSpec(
                    "notifications.getDestination",
                    "notifications",
                    "GET",
                    "/notifications/v1/destinations/{destinationId}",
                    List.of(200),
                    true,
                    false,
                    Set.of("destinationId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "notifications.deleteDestination",
                    "notifications",
                    "DELETE",
                    "/notifications/v1/destinations/{destinationId}",
                    List.of(200),
                    true,
                    false,
                    Set.of("destinationId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "listingsItems.getListingsItem",
                    "listingsItems",
                    "GET",
                    "/listings/2021-08-01/items/{sellerId}/{sku}",
                    List.of(200),
                    false,
                    false,
                    Set.of("sellerId", "sku"),
                    Set.of("marketplaceIds"),
                    Set.of()),
            new SpApiOperationSpec(
                    "listingsItems.putListingsItem",
                    "listingsItems",
                    "PUT",
                    "/listings/2021-08-01/items/{sellerId}/{sku}",
                    List.of(200),
                    false,
                    true,
                    Set.of("sellerId", "sku"),
                    Set.of("marketplaceIds"),
                    Set.of("attributes", "productType")),
            new SpApiOperationSpec(
                    "listingsItems.patchListingsItem",
                    "listingsItems",
                    "PATCH",
                    "/listings/2021-08-01/items/{sellerId}/{sku}",
                    List.of(200),
                    false,
                    true,
                    Set.of("sellerId", "sku"),
                    Set.of("marketplaceIds"),
                    Set.of("patches", "productType")),
            new SpApiOperationSpec(
                    "listingsItems.deleteListingsItem",
                    "listingsItems",
                    "DELETE",
                    "/listings/2021-08-01/items/{sellerId}/{sku}",
                    List.of(200),
                    false,
                    false,
                    Set.of("sellerId", "sku"),
                    Set.of("marketplaceIds"),
                    Set.of()),
            new SpApiOperationSpec(
                    "listingsItems.searchListingsItems",
                    "listingsItems",
                    "GET",
                    "/listings/2021-08-01/items/{sellerId}",
                    List.of(200),
                    false,
                    false,
                    Set.of("sellerId"),
                    Set.of("marketplaceIds"),
                    Set.of()),
            new SpApiOperationSpec(
                    "productPricing.getFeaturedOfferExpectedPriceBatch",
                    "productPricing",
                    "POST",
                    "/batches/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice",
                    List.of(200),
                    false,
                    true,
                    Set.of(),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "productPricing.getCompetitiveSummary",
                    "productPricing",
                    "POST",
                    "/batches/products/pricing/2022-05-01/items/competitiveSummary",
                    List.of(200),
                    false,
                    true,
                    Set.of(),
                    Set.of(),
                    Set.of("requests")),
            new SpApiOperationSpec(
                    "catalogItems.searchCatalogItems",
                    "catalogItems",
                    "GET",
                    "/catalog/2022-04-01/items",
                    List.of(200),
                    false,
                    false,
                    Set.of(),
                    Set.of("marketplaceIds"),
                    Set.of()),
            new SpApiOperationSpec(
                    "catalogItems.getCatalogItem",
                    "catalogItems",
                    "GET",
                    "/catalog/2022-04-01/items/{asin}",
                    List.of(200),
                    false,
                    false,
                    Set.of("asin"),
                    Set.of("marketplaceIds"),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listInboundPlans",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans",
                    List.of(200),
                    false,
                    false,
                    Set.of(),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.createInboundPlan",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans",
                    List.of(202),
                    false,
                    true,
                    Set.of(),
                    Set.of(),
                    Set.of("destinationMarketplaces", "items", "sourceAddress")),
            new SpApiOperationSpec(
                    "fbaInbound.getInboundPlan",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listInboundPlanBoxes",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/boxes",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.cancelInboundPlan",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/cancellation",
                    List.of(202),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listInboundPlanItems",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/items",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.updateInboundPlanName",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/name",
                    List.of(204),
                    false,
                    true,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of("name")),
            new SpApiOperationSpec(
                    "fbaInbound.listPackingGroupBoxes",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/packingGroups/{packingGroupId}/boxes",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "packingGroupId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listPackingGroupItems",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/packingGroups/{packingGroupId}/items",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "packingGroupId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.setPackingInformation",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/packingInformation",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of("packageGroupings")),
            new SpApiOperationSpec(
                    "fbaInbound.listPackingOptions",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/packingOptions",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.generatePackingOptions",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/packingOptions",
                    List.of(202),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.confirmPackingOption",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/packingOptions/{packingOptionId}/confirmation",
                    List.of(202),
                    false,
                    false,
                    Set.of("inboundPlanId", "packingOptionId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listInboundPlanPallets",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/pallets",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listPlacementOptions",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/placementOptions",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.generatePlacementOptions",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/placementOptions",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.confirmPlacementOption",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/placementOptions/{placementOptionId}/confirmation",
                    List.of(202),
                    false,
                    false,
                    Set.of("inboundPlanId", "placementOptionId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.getShipment",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listShipmentBoxes",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/boxes",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listShipmentContentUpdatePreviews",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/contentUpdatePreviews",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.generateShipmentContentUpdatePreviews",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/contentUpdatePreviews",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of("boxes", "items")),
            new SpApiOperationSpec(
                    "fbaInbound.getShipmentContentUpdatePreview",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/contentUpdatePreviews/{contentUpdatePreviewId}",
                    List.of(200),
                    false,
                    false,
                    Set.of("contentUpdatePreviewId", "inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.confirmShipmentContentUpdatePreview",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/contentUpdatePreviews/{contentUpdatePreviewId}/confirmation",
                    List.of(202),
                    false,
                    false,
                    Set.of("contentUpdatePreviewId", "inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.getDeliveryChallanDocument",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/deliveryChallanDocument",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listDeliveryWindowOptions",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/deliveryWindowOptions",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.generateDeliveryWindowOptions",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/deliveryWindowOptions",
                    List.of(202),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.confirmDeliveryWindowOptions",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/deliveryWindowOptions/{deliveryWindowOptionId}/confirmation",
                    List.of(202),
                    false,
                    false,
                    Set.of("deliveryWindowOptionId", "inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.listShipmentItems",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/items",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.updateShipmentName",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/name",
                    List.of(204),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of("name")),
            new SpApiOperationSpec(
                    "fbaInbound.listShipmentPallets",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/pallets",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.cancelSelfShipAppointment",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/selfShipAppointmentCancellation",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.getSelfShipAppointmentSlots",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/selfShipAppointmentSlots",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.generateSelfShipAppointmentSlots",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/selfShipAppointmentSlots",
                    List.of(201),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.scheduleSelfShipAppointment",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/selfShipAppointmentSlots/{slotId}/schedule",
                    List.of(200),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId", "slotId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.updateShipmentSourceAddress",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/sourceAddress",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of("address")),
            new SpApiOperationSpec(
                    "fbaInbound.updateShipmentTrackingDetails",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/trackingDetails",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId", "shipmentId"),
                    Set.of(),
                    Set.of("trackingDetails")),
            new SpApiOperationSpec(
                    "fbaInbound.listTransportationOptions",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/transportationOptions",
                    List.of(200),
                    false,
                    false,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.generateTransportationOptions",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/transportationOptions",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of("placementOptionId", "shipmentTransportationConfigurations")),
            new SpApiOperationSpec(
                    "fbaInbound.confirmTransportationOptions",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/transportationOptions/confirmation",
                    List.of(202),
                    false,
                    true,
                    Set.of("inboundPlanId"),
                    Set.of(),
                    Set.of("transportationSelections")),
            new SpApiOperationSpec(
                    "fbaInbound.listItemComplianceDetails",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/items/compliance",
                    List.of(200),
                    false,
                    false,
                    Set.of(),
                    Set.of("marketplaceId", "mskus"),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.updateItemComplianceDetails",
                    "fbaInbound",
                    "PUT",
                    "/inbound/fba/2024-03-20/items/compliance",
                    List.of(202),
                    false,
                    true,
                    Set.of(),
                    Set.of("marketplaceId"),
                    Set.of("msku", "taxDetails")),
            new SpApiOperationSpec(
                    "fbaInbound.createMarketplaceItemLabels",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/items/labels",
                    List.of(200),
                    false,
                    true,
                    Set.of(),
                    Set.of(),
                    Set.of("labelType", "marketplaceId", "mskuQuantities")),
            new SpApiOperationSpec(
                    "fbaInbound.listPrepDetails",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/items/prepDetails",
                    List.of(200),
                    false,
                    false,
                    Set.of(),
                    Set.of("marketplaceId", "mskus"),
                    Set.of()),
            new SpApiOperationSpec(
                    "fbaInbound.setPrepDetails",
                    "fbaInbound",
                    "POST",
                    "/inbound/fba/2024-03-20/items/prepDetails",
                    List.of(202),
                    false,
                    true,
                    Set.of(),
                    Set.of(),
                    Set.of("marketplaceId", "mskuPrepDetails")),
            new SpApiOperationSpec(
                    "fbaInbound.getInboundOperationStatus",
                    "fbaInbound",
                    "GET",
                    "/inbound/fba/2024-03-20/operations/{operationId}",
                    List.of(200),
                    false,
                    false,
                    Set.of("operationId"),
                    Set.of(),
                    Set.of())
    );

    private static final Map<String, SpApiOperationSpec> BY_OPERATION_ID =
            OPERATIONS.stream().collect(Collectors.toUnmodifiableMap(
                    SpApiOperationSpec::operationId, Function.identity()));

    private static final Map<String, List<SpApiOperationSpec>> BY_FAMILY =
            OPERATIONS.stream().collect(Collectors.collectingAndThen(
                    Collectors.groupingBy(
                            SpApiOperationSpec::family,
                            LinkedHashMap::new,
                            Collectors.toUnmodifiableList()),
                    Map::copyOf));

    private SpApiOperationCatalog() {
    }

    public static List<SpApiOperationSpec> operations() {
        return OPERATIONS;
    }

    public static Optional<SpApiOperationSpec> find(String operationId) {
        return operationId == null
                ? Optional.empty()
                : Optional.ofNullable(BY_OPERATION_ID.get(operationId));
    }

    public static List<SpApiOperationSpec> operationsFor(String family) {
        return family == null ? List.of() : BY_FAMILY.getOrDefault(family, List.of());
    }
}
