-- Feeds 的 DONE 只代表处理结束，不等于全部消息 accepted。
-- 增加 PARTIAL 终态后，任务状态机为：
-- PENDING -> PROCESSING -> SUBMITTED -> SUCCESS / PARTIAL / FAILED / TIMEOUT。
ALTER TABLE amz_listing_copy_task
    MODIFY COLUMN status VARCHAR(20) DEFAULT 'PENDING'
    COMMENT 'PENDING/PROCESSING/SUBMITTED/SUCCESS/PARTIAL/FAILED/TIMEOUT';
